### ISSUE TITLE
Home for `transforms` subpackage

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/PE#25]
The current `transforms` submodule of the `data` library implements the same transform base class and whitening transform as BBHnet.  There is an open [issue](ML4GW/ml4gw#6) in ml4gw to incorporate the whitening transform. 

The `StandardScalerTransform` should probably be generalized to allow, e.g., standardization of `(batch_size, n_data)` tensors, as well as `(batch_size, n_channels, n_data)` tensors and added in `ml4gw` as well.

**Comment by deepchatterjeeligo** [comment]
Shall we close this since this is migrated to ml4gw?
