### ISSUE TITLE
Home for `trainify` wrapper

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/PE#28]
The `trainify` wrapper has been cloned in its entirety from bbhnet. I think once [this](ML4GW/typeo/#8) issue is resolved in typeo, the logic behind both the `trainify` and `architecturize` wrappers will be abstracted away into typeo.

**Comment by deepchatterjeeligo** [comment]
The link above does not work for me. Is the issue still open?

**Comment by deepchatterjeeligo** [comment]
Closed by typeo updates.
