### ISSUE TITLE
Migrate to `ml4gw` standard scaler

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/PE#37]
`ml4gw` has implemented a [standard scaler](https://github.com/ML4GW/ml4gw/blob/main/ml4gw/transforms/scaler.py#L7) that conveniently has the ability to apply the inverse transformation. Although this object is documented as being for timeseries, I think we can use this for standardizing our parameters. Each "channel" will correspond to a different parameter (e.g frequency, quality)

**Comment by deepchatterjeeligo** [comment]
closed by ed89e93b7070ed8ed70b1de99202fe470f7dc6c7
