### ISSUE TITLE
`trainer` script tweaks

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/PE#44]
Issues #43 #42 will require changing a few things in the trainer script:

1. The [`architecture`](https://github.com/ML4GW/PE/blob/main/libs/trainer/mlpe/trainer/trainer.py#L202) should take `(param_dim, n_ifos, strain_dim)` as its shape initializer.
2. the `strain_dim` should be inferred [here](https://github.com/ML4GW/PE/blob/main/libs/trainer/mlpe/trainer/trainer.py#L194) , not the `context_dim` which will be inferred by the embedding_net passed to the flow.

**Comment by deepchatterjeeligo** [comment]
Closing since both points above are taken care of.
