### ISSUE TITLE
Automate Analysis 

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/PE#47]
Now that we have something that resembles reasonable results, we should automate the analysis of the testing set.

For now I think all this should include is production of posteriors, and a PP plot. We can think about how a `vizapp` analogous to BBHnet's might fit in.

**Comment by deepchatterjeeligo** [comment]
I was thinking of making a similar issue. We should have a project called "sampling" which would generate samples from the testing set, and have a module to generate plots like PP plot for the whole testing set, but also corner plots for individual samples.

**Comment by deepchatterjeeligo** [comment]
Shall we close this?
