### ISSUE TITLE
Function that converts phi to ra based on gpstime of event

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/PE#63]
Write a utility function that converts from our measured `phi` to the true `ra` value based on the gpstime of the event. Use this function before plotting posteriors so we can compare directly with bilby.

**Comment by deepchatterjeeligo** [comment]
The function is basically the snippet mentioned here: https://github.com/ML4GW/PE/pull/66#discussion_r1142790074

**Comment by deepchatterjeeligo** [comment]
This is now done in the aps-dev branch. Close once merged to main.
