### ISSUE TITLE
Generate signals on the fly

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/PE#78]
Given we have an analytical model for Sine Gaussians that we can (most likely) implement in torch, we should probably just be generating these on GPU during training. I imagine sampling random parameters with `bilby` may bottleneck us, so it might also be necessary to implement some of these priors in torch

**Comment by EthanMarx** [comment]
The only distribution not supported by `ml4gw` currently is `LogUniform` which is easy to do

**Comment by deepchatterjeeligo** [comment]
Being worked on here: https://github.com/ML4GW/ml4gw/tree/dev
